### ISSUE TITLE
Accessing thru another site.

### ISSUE THREAD

**Issue by Crazydmz** [nattthebear/ff12characterplanner#38]
I have a [Job Planner in Google Sheets](https://docs.google.com/spreadsheets/d/1d03nJU_wfwHGQSPHRLMIkE2F53sQbELf7Ahqds_NJ2U/edit?usp=sharing) which I would like to point them to your website once they select their jobs.  

I'd like to send them to your site with the job filled out and all the LP Spent clinking 100 times for your site is a bit taxing.  Perhaps you could have a button to do that. But if I could send them to you with a link I'd be a rather good way to plan.

My FFXII - Helper is a bunch of list for FFXII and Job Planner is rather basic but easy.

**Comment by nattthebear** [comment]
That looks like an interesting tool.

I don't have a "assign all LP" button because it's not how I envision my planner being used in most situations:  Usually, you'd just select the jobs and mist licenses, and then that's it.  But it could be useful, and I may add it if I can find space for the button.  Tracked as https://github.com/nattthebear/ff12characterplanner/issues/5.

My planner does support hotlinks in with licenses filled out already.  If you'd like to generate them from within your tool, you'll need to know the shape of the boards and where all the licenses are on them, ie, something similar to the contents of https://github.com/nattthebear/ff12characterplanner/blob/master/src/data/Boards.ts.  If you do have that, then generating the URLs is just a bit of base64 fiddling, see https://github.com/nattthebear/ff12characterplanner/blob/master/src/model/PartyModel.ts#L362.  Would it help if I wrote out a description for the algorithm used to generate URLs?

**Comment by Crazydmz** [comment]
Yes it would. I haven't programmed in a very long time.  I'm fluent in VB, VBA, and C+ (Ok in C#).  I can program, but I need a little help in general. I've always hated HTML so I've never tried very hard @ it.

Just started to learn Java Script for Google Sheets.  So any help is very much appreciated.  HTML isn't a language I still say.

**Comment by nattthebear** [comment]
I've added documentation for encoding and decoding URLs at https://github.com/nattthebear/ff12characterplanner/blob/master/Urls.md.  Let me know if there's anything in there that needs clarification.

**Comment by Crazydmz** [comment]
> I've added documentation for encoding and decoding URLs at https://github.com/nattthebear/ff12characterplanner/blob/master/Urls.md. Let me know if there's anything in there that needs clarification.

Thanks... Not sure if anyone actually uses my buttons in my Spreadsheet, but it does link to you now.  Push a button after selecting jobs and sends to you preconfigured and filled out to the point where they can plan who gets which Aeon/Esper.  If I knew how to make a select system in google sheets I wouldn't want your link as much as I do now.

Your vision was immediate planning of LP points, my vision was long term planning of Espers.  Thanks for your help let me know if people are using link.

**Comment by nattthebear** [comment]
Thanks for linking to my program!  Hopefully it will be able to help more people plan their way through this game.

> let me know if people are using link.

I'll certainly pass on any feedback I get, but note that I have no telemetry, analytics, or other observability systems on my planner so I won't be able to give any visitor referrer statistics.

Closing this issue as completed.
