### ISSUE TITLE
Yagyu Darkblade & Mesa Missing from DPS

### ISSUE THREAD

**Issue by Exergist** [nattthebear/ff12characterplanner#45]
I noticed that the DPS stats for using the Yagyu Darkblade as well as the Mesa are missing. Here's an example with Balthier as a Shikari and White Mage:

![image](https://github.com/nattthebear/ff12characterplanner/assets/31357974/b4ffccf5-c582-4575-8650-dcf04b5228bf)

While all the ninja swords are shown in the license pool, the two blades are missing in the DPS table. Upon further inspection it seems that none of the [Zodiac Age ninja swords](https://finalfantasy.fandom.com/wiki/Ninja_blade_(weapon_type)#Final_Fantasy_XII) are shown. Is this intentional?

**Comment by nattthebear** [comment]
You're only shown DPS stats for weapons the character can equip given the licenses the character has access to.  The DPS planner assumes that any license that's acquired (white shaded), or not hidden behind a mist license (grey shaded) is available, but it won't take any license behind a mist license (yellow shaded) automatically because you can't necessarily have them all.

**Comment by nattthebear** [comment]
If you assign any of the quickenings to a hunter, the ninja sword(s) unlocked will show up in the dps planner.
